// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ratelimit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single rate limit check request
type RateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`  // unique identifier for the client (e.g. IP, API key)
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`                 // max tokens / max requests allowed in the window
	Rate          int32                  `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`                         // tokens refilled per second (token bucket only)
	WindowMs      int64                  `protobuf:"varint,4,opt,name=window_ms,json=windowMs,proto3" json:"window_ms,omitempty"` // window size in milliseconds (sliding window only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitRequest) Reset() {
	*x = RateLimitRequest{}
	mi := &file_proto_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRequest) ProtoMessage() {}

func (x *RateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRequest.ProtoReflect.Descriptor instead.
func (*RateLimitRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RateLimitRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RateLimitRequest) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *RateLimitRequest) GetWindowMs() int64 {
	if x != nil {
		return x.WindowMs
	}
	return 0
}

// The response telling the caller whether they're allowed through
type RateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`                                 // true = request is allowed
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`                             // tokens or slots remaining
	RetryAfterMs  int64                  `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // if denied, how long to wait in ms
	Algorithm     string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`                              // which algorithm produced this response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitResponse) Reset() {
	*x = RateLimitResponse{}
	mi := &file_proto_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitResponse) ProtoMessage() {}

func (x *RateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitResponse.ProtoReflect.Descriptor instead.
func (*RateLimitResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *RateLimitResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *RateLimitResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *RateLimitResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

var File_proto_ratelimit_proto protoreflect.FileDescriptor

const file_proto_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ratelimit.proto\x12\tratelimit\"|\n" +
	"\x10RateLimitRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x05R\x04rate\x12\x1b\n" +
	"\twindow_ms\x18\x04 \x01(\x03R\bwindowMs\"\x8f\x01\n" +
	"\x11RateLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\x03R\fretryAfterMs\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm2\xad\x01\n" +
	"\vRateLimiter\x12M\n" +
	"\x10CheckTokenBucket\x12\x1b.ratelimit.RateLimitRequest\x1a\x1c.ratelimit.RateLimitResponse\x12O\n" +
	"\x12CheckSlidingWindow\x12\x1b.ratelimit.RateLimitRequest\x1a\x1c.ratelimit.RateLimitResponseB9Z7github.com/BlissPhinehas/distributed-rate-limiter/protob\x06proto3"

var (
	file_proto_ratelimit_proto_rawDescOnce sync.Once
	file_proto_ratelimit_proto_rawDescData []byte
)

func file_proto_ratelimit_proto_rawDescGZIP() []byte {
	file_proto_ratelimit_proto_rawDescOnce.Do(func() {
		file_proto_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ratelimit_proto_rawDesc), len(file_proto_ratelimit_proto_rawDesc)))
	})
	return file_proto_ratelimit_proto_rawDescData
}

var file_proto_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ratelimit_proto_goTypes = []any{
	(*RateLimitRequest)(nil),  // 0: ratelimit.RateLimitRequest
	(*RateLimitResponse)(nil), // 1: ratelimit.RateLimitResponse
}
var file_proto_ratelimit_proto_depIdxs = []int32{
	0, // 0: ratelimit.RateLimiter.CheckTokenBucket:input_type -> ratelimit.RateLimitRequest
	0, // 1: ratelimit.RateLimiter.CheckSlidingWindow:input_type -> ratelimit.RateLimitRequest
	1, // 2: ratelimit.RateLimiter.CheckTokenBucket:output_type -> ratelimit.RateLimitResponse
	1, // 3: ratelimit.RateLimiter.CheckSlidingWindow:output_type -> ratelimit.RateLimitResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ratelimit_proto_init() }
func file_proto_ratelimit_proto_init() {
	if File_proto_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ratelimit_proto_rawDesc), len(file_proto_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ratelimit_proto_goTypes,
		DependencyIndexes: file_proto_ratelimit_proto_depIdxs,
		MessageInfos:      file_proto_ratelimit_proto_msgTypes,
	}.Build()
	File_proto_ratelimit_proto = out.File
	file_proto_ratelimit_proto_goTypes = nil
	file_proto_ratelimit_proto_depIdxs = nil
}
